- web/package-lock.json
- web/package.json
- web/src/components/OLMap.js
- web/src/pages/district/index.js
move the apollo query out and this will fix the refresh problem
> fix: update map to fix refresh problem

- web/.prettierrc
- web/package-lock.json
- web/package.json
- web/src/App.js
- web/src/App.test.js
- web/src/components/AddressSearcher.js
- web/src/components/BorderLinearProgress.js
- web/src/components/OLMap.js
- web/src/components/PeopleSearcher.js
- web/src/data/csv2json.js
- web/src/data/format-json.js
- web/src/index.js
- web/src/layout/NavBar.js
- web/src/pages/district/index.js
- web/src/pages/notfound/index.js
- web/src/pages/profile/index.js
- web/src/pages/search/index.js
- web/src/serviceWorker.js
- web/src/ui/theme/index.js
- web/src/utils/features.js
this is a plugin that can enforce the format of the codes (e.g. spacing/tabs/semicolons)
and it has a prehook for git commit
> feat: add prettier for formatting the code

- web/.env
- web/package.json
- web/src/components/district/CandidateList.js
- web/src/components/district/DistrictCard.js
- web/src/components/district/MainAreas.js
- web/src/pages/district/index.js
- web/src/utils/responsive.js
- use more styled components
- extract to different components
> refak(distrcit): refactor the district page

- web/package-lock.json
- web/package.json
- web/src/components/TreeMap.js
**Usage:** 
`<TreeMap id="chart1"  data={chartJSON} width='100%' height='400px'/>`
The data is in json format. Example:
const chartJSON =  {
"type":"treemap",
"options":{
"split-type":"balanced",
"color-type":"palette",
"palette": ["#f44336","#29b6f6","#ab47bc","#ffc107","#5c6bc0","#009688"]
},
"plotarea":{
"margin": "0 0 35 0"
},
"series":[
{
"text":"North America",
"children":[
{
"text":"United States",
"children":[
{
"text":"Texas",
"value":90
}
]
},
{
"text":"Canada",
"value":113
},
{
"text":"Mexico",
"value":78
}
]
},
{
"text":"Europe",
"children":[
{
"text":"France",
"value":42
},
{
"text":"Spain",
"value":28
}
]
},
{
"text":"Africa",
"children":[
{
"text":"Egypt",
"value":22
},
{
"text":"Congo",
"value":38
}
]
},
{
"text":"Asia",
"children":[
{
"text":"India",
"value":92
},
{ …
> Add TreeMap Component

- web/public/404.html
- web/public/index.html
- web/src/index.js
- Remove "#" in URL using https://github.com/rafrex/spa-github-pages
> Switch to use BrowserRouter with spa-github-pages

- web/src/App.js
- web/src/components/organisms/Footer.js
- web/src/components/organisms/SearchTab.js
- Remove unused drawer close button shown in desktop
- Fix width limited scrollbar when shown in desktop
> Fix desktop UI

- web/src/components/molecules/DistrictSelector.js
- web/src/utils/helper.js
- Fix DistrictSelector to make Constituency clickable
> Fix DistrictSelector to make Constituency clickable

- web/src/components/molecules/DistrictSelector.js
- web/src/components/organisms/search-drawer/SearchMenu.js
- web/src/utils/helper.js
- Replace SearchMenu with new SearchTab
> Replace SearchMenu with new SearchTab

- web/src/components/molecules/DistrictSelector.js
- web/src/components/organisms/SearchMenu.js
- Tune ExpansionPanel performance by enabling unmountOnExit
> Tune Drawer Performance

- web/package-lock.json
- web/src/components/DCCACompareMap.js
Ref to [Battleground] Enhance the UI of ugly zoom in / zoom out button
> Hide OL5 Control

- web/src/App.js
- web/src/components/molecules/DistrictSelector.js
- web/src/components/molecules/candidate/CandidatesTableContent.js
- web/src/components/molecules/constituency/ConstituencyTableContent.js
- web/src/components/molecules/district/DistrictTableContent.js
- web/src/components/molecules/district/DistrictsTable.js
- web/src/components/pages/district/all.js
- web/src/queries/gql.js
- Turn district overview page to a table (http://localhost:3000/district/2019/A)
- Add a URL to display table for all districts (http://localhost:3000/district/2019)
> District Table

- web/src/components/pages/profile/index.js
- add info icon
- add tooltips
- tooltips box in white background with black text
> Add a info icon

- web/src/components/molecules/AddressSearcher.js
> Remove duplicate records in AddressSearch

- web/src/components/atoms/CampSelector.js
- web/src/components/molecules/candidate/CandidatesTableContent.js
- web/src/components/molecules/constituency/ConstituencyTableContent.js
- web/src/components/molecules/district/DistrictTableContent.js
- web/src/components/molecules/district/DistrictsTable.js
1. Add CampSelector
2. Integrate CampSelector in DistrictsTable and its children
https://trello.com/c/1QgKaM2p/221-district-all-overview-filter-by-camp
> Filter by Camp

- web/src/App.js
- web/src/components/pages/SearchDrawer.js
Problems: If you click the menu button in [https://vote4.hk/district/2019](https://vote4.hk/district/2019), it will take a while time to response.
fix:
Avoid the useless rerender in App.js
> fix: avoid useless rerender

- web/src/components/atoms/Loading.js
Fix the loading spinner position to vertically centered
Spinner moves to the top.
Showing the spinner at the center when loading.
no.
> fix(UIUX): Loading spinner vertically center

- ssr/pages/district/[year]/[code].js
- ssr/pages/profile/[name]/[id].js
- web/public/index.html
Change and recorder meta based on Search Console
Make SSR and React metas more consistent
Show old meta
Show new meta
No
Nothing
> Tune HTML Meta

- .github/PULL_REQUEST_TEMPLATE
Pull Request Template Update
Add i18n requirement to Pull Request Template
Nope
> Add i18n requirement to Pull Request Template

- web/src/components/atoms/CampSelector.js
- web/src/components/molecules/DistrictSelector.js
- web/src/components/templates/CampCompareChartContainer.js
- web/src/components/templates/Summary.js
- web/src/locales/en/translation.json
- web/src/locales/zh/translation.json
- web/src/queries/gql.js
- web/src/utils/helper.js
Add withLanguage for displaying names based on selected language
> Add withLanguage for displaying names based on selected language

- README.md
Docs update. Add i18n to README.md.
> Add i18n to README.md

- README.md
> Fix typos in README.md & Add example paths

- README.md
Docs Update
No i18next interpolation in README.md
Add i18next interpolation to README.md
No
> Add i18next interpolation to README.md

- ssr/package-lock.json
- ssr/package.json
- ssr/pages/district/[year]/[code].js
- ssr/pages/profile/[name]/[id].js
- web/public/index.html
* Add `next-seo` for easier generation of meta
* Add Google Structured Data in an attempt to improve SEO
* Add `fb:app_id` in meta for getting facebook insights
* No Google Structured Data and `fb:app_id` in `<meta>`
* Expect Google Structured Data and `fb:app_id` in `<meta>` for the following urls
* https://vote4.hk
* https://meta.vote4.hk/district/2019/*
* https://meta.vote4.hk/profile/*
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this …
> Add Structured Data and FB App ID

- web/src/App.js
- web/src/components/organisms/Footer.js
- web/src/components/organisms/SearchMenu.js
- web/src/components/pages/landing/index.js
- web/src/components/pages/support-us/index.js
remove the floating button and use the footer instead
remove any phrase "support us" and use "support g0vhk" and "about us" instead
> feat: about us

- web/package-lock.json
- web/src/components/atoms/charts/StackedNormalizedHorizontalBarChart.js
- web/src/components/molecules/LoadingButton.js
- web/src/components/pages/district/overview.js
- web/src/components/templates/DistrictCampCompareChartContainer.js
district page will now show a result simulator
No.
> feat: add simulation chart for district

- web/src/components/templates/Summary.js
- web/src/queries/gql.js
Reverts cswbrian/district-councils-dashboard#95
> Revert "Add 自動當選 + 翻盤 at landing page "

- web/src/components/pages/profile/index.js
- tried to fix the image on mobile (needs to test on mobile after deployment)
- added candidate number to profile details page
> add candidate number to profile details page

- ssr/components/meta/constituency.js
- ssr/components/meta/district.js
- ssr/components/meta/profile.js
- ssr/lib/gql.js
- ssr/pages/[lang]/district/[year]/[code].js
- ssr/pages/[lang]/profile/[name]/[id].js
- ssr/server/app.js
* Support sharing meta of "/en" and "/zh" using SSR
* **WARNING**: Still need to translate the meta under `ssr/components/meta`
* https://meta.vote4.hk/en/profile/%E5%BC%B5%E6%96%87%E5%B5%A9/60564081-3681-416c-a2a9-7b000d6c49f0 is 404
* https://meta.vote4.hk/en/profile/%E5%BC%B5%E6%96%87%E5%B5%A9/60564081-3681-416c-a2a9-7b000d6c49f0 will show proper meta
> Support locale routes for SSR

- web/package-lock.json
- web/package.json
- web/src/components/organisms/GlobalDisclaimer.js
> Dismissing global disclaimer for revisiting

- web/package-lock.json
- web/src/components/organisms/MobileAppBar.js
- web/src/components/organisms/ScrollableTabs.js
- web/src/components/pages/profile/index.js
> minor changes on css and change mobile app title bar

- web/src/components/pages/battleground/index.js
…switch
Bug fix
multiple clicks on the map failed, after enabling the language switch.
> Fix " issue on multiple click on the map, after enabling the language switch"

- .gitignore
- web/package-lock.json
- web/package.json
- web/src/App.js
- web/src/components/organisms/Footer.js
> Dynamic page loading

- web/package-lock.json
- web/package.json
- web/src/components/pages/landing/CenterText.js
- web/src/components/pages/landing/CountdownDate.js
- web/src/components/pages/landing/HeadAlert.js
- web/src/components/pages/landing/index.js
- web/src/withQuery.js
> merge graphql in landing page

- web/src/components/organisms/Footer.js
> fix footer fb exception issue
